import { Academy, AttendanceRecord, Child, HomeworkItem, AppNotification, SchoolClassPeriod, SchoolMealItem } from './types';

export const INITIAL_CHILDREN: Child[] = [
  {
    id: 'child-1',
    name: '이민준',
    age: 15,
    schoolName: '대치중학교',
    grade: '중학교 2학년',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    phone: '010-8291-4921',
    batteryLevel: 84,
    isCharging: false,
    gpsPermission: 'always',
    isOnline: true,
    pairingCode: 'SK-8924',
    currentLocation: {
      lat: 37.4985,
      lng: 127.0592,
      accuracy: 8,
      address: '서울특별시 강남구 대치동 은마아파트 사거리 인근',
      updatedAt: '방금 전 (1분 이내)',
    },
  },
  {
    id: 'child-2',
    name: '이서연',
    age: 12,
    schoolName: '서울대치초등학교',
    grade: '초등학교 5학년',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    phone: '010-9428-1102',
    batteryLevel: 68,
    isCharging: true,
    gpsPermission: 'always',
    isOnline: true,
    pairingCode: 'SK-4190',
    currentLocation: {
      lat: 37.4960,
      lng: 127.0622,
      accuracy: 12,
      address: '서울특별시 강남구 대치동 한티역 2번 출구 부근',
      updatedAt: '3분 전',
    },
  },
];

export const INITIAL_ACADEMIES: Academy[] = [
  {
    id: 'acad-1',
    name: '대치 엠스쿨 수학학원',
    subject: '수학 (심화과정)',
    classroom: '본관 302호',
    color: '#3B82F6', // Blue
    address: '서울특별시 강남구 남부순환로 2936 윈플러스빌딩 3층',
    lat: 37.4982,
    lng: 127.0598,
    geofenceRadius: 10, // 10 meters precision
    days: [1, 3, 5], // Mon, Wed, Fri
    startTime: '17:00',
    endTime: '19:00',
    teacherName: '박준혁 원장',
    teacherContact: '02-555-8910',
    shuttle: {
      enabled: true,
      busName: '노란 1호차 (70고 8821)',
      driverPhone: '010-3321-7712',
      pickupLocation: '은마아파트 3동 정문 앞',
      pickupTime: '16:30',
      dropoffLocation: '은마아파트 3동 정문 앞',
      dropoffTime: '19:20',
    },
  },
  {
    id: 'acad-2',
    name: '청담 에이프릴 어학원',
    subject: '영어 (Junior TOEFL)',
    classroom: '5층 스마트랩',
    color: '#8B5CF6', // Purple
    address: '서울특별시 강남구 도곡로 408 디마크빌딩 5층',
    lat: 37.4963,
    lng: 127.0625,
    geofenceRadius: 10,
    days: [2, 4], // Tue, Thu
    startTime: '16:30',
    endTime: '18:30',
    teacherName: 'Jessica Kim',
    teacherContact: '02-567-3341',
    shuttle: {
      enabled: true,
      busName: '초록 2호차 (62노 3419)',
      driverPhone: '010-4491-0182',
      pickupLocation: '대치역 7번 출구 버스정류장',
      pickupTime: '16:05',
      dropoffLocation: '대치역 7번 출구 버스정류장',
      dropoffTime: '18:50',
    },
  },
  {
    id: 'acad-3',
    name: '미래탐구 과학실험관',
    subject: '과학 (물화생지 탐구)',
    classroom: '실험동 201호',
    color: '#10B981', // Emerald
    address: '서울특별시 강남구 삼성로 212 은마종합상가 B블럭 2층',
    lat: 37.5002,
    lng: 127.0575,
    geofenceRadius: 10,
    days: [6], // Sat
    startTime: '10:00',
    endTime: '13:00',
    teacherName: '강태우 팀장',
    teacherContact: '02-553-9002',
    shuttle: {
      enabled: false,
      busName: '',
      driverPhone: '',
      pickupLocation: '',
      pickupTime: '',
      dropoffLocation: '',
      dropoffTime: '',
    },
  },
  {
    id: 'acad-4',
    name: '경희대 백호 태권도장',
    subject: '예체능 (품새 및 줄넘기)',
    classroom: '지하 1층 대수련실',
    color: '#F59E0B', // Amber
    address: '서울특별시 강남구 선릉로64길 18 2층',
    lat: 37.4952,
    lng: 127.0581,
    geofenceRadius: 10,
    days: [1, 2, 3, 4, 5], // Weekdays
    startTime: '15:20',
    endTime: '16:20',
    teacherName: '이관우 관장',
    teacherContact: '02-538-1290',
    shuttle: {
      enabled: true,
      busName: '백호 스타리아 (12허 9940)',
      driverPhone: '010-8911-3820',
      pickupLocation: '학교 후문 스쿨존 픽업존',
      pickupTime: '15:05',
      dropoffLocation: '학원 빌딩 앞',
      dropoffTime: '16:30',
    },
  },
];

export const INITIAL_ATTENDANCE_LOGS: AttendanceRecord[] = [
  {
    id: 'att-1',
    childId: 'child-1',
    academyId: 'acad-1',
    academyName: '대치 엠스쿨 수학학원',
    date: '2026-09-15',
    status: 'present',
    checkInTime: '16:48',
    checkOutTime: '19:04',
    isManual: false,
    geofenceDistance: 24,
  },
  {
    id: 'att-2',
    childId: 'child-1',
    academyId: 'acad-4',
    academyName: '경희대 백호 태권도장',
    date: '2026-09-15',
    status: 'present',
    checkInTime: '15:14',
    checkOutTime: '16:22',
    isManual: false,
    geofenceDistance: 18,
  },
  {
    id: 'att-3',
    childId: 'child-1',
    academyId: 'acad-2',
    academyName: '청담 에이프릴 어학원',
    date: '2026-09-14',
    status: 'manual_checked',
    checkInTime: '16:32',
    checkOutTime: '18:35',
    isManual: true,
    manualReason: '지하 1층 엘리베이터 이동 중 GPS 일시 음영으로 학부모 수동 확인 처리',
    geofenceDistance: 110,
  },
  {
    id: 'att-4',
    childId: 'child-1',
    academyId: 'acad-1',
    academyName: '대치 엠스쿨 수학학원',
    date: '2026-09-12',
    status: 'present',
    checkInTime: '16:51',
    checkOutTime: '19:02',
    isManual: false,
    geofenceDistance: 31,
  },
  {
    id: 'att-5',
    childId: 'child-1',
    academyId: 'acad-3',
    academyName: '미래탐구 과학실험관',
    date: '2026-09-13',
    status: 'present',
    checkInTime: '09:52',
    checkOutTime: '13:06',
    isManual: false,
    geofenceDistance: 15,
  },
  {
    id: 'att-6',
    childId: 'child-1',
    academyId: 'acad-1',
    academyName: '대치 엠스쿨 수학학원',
    date: '2026-09-10',
    status: 'late',
    checkInTime: '17:08',
    checkOutTime: '19:05',
    isManual: false,
    geofenceDistance: 45,
  },
  {
    id: 'att-7',
    childId: 'child-2',
    academyId: 'acad-4',
    academyName: '경희대 백호 태권도장',
    date: '2026-09-15',
    status: 'present',
    checkInTime: '15:16',
    checkOutTime: '16:21',
    isManual: false,
    geofenceDistance: 22,
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    childId: 'child-1',
    childName: '이민준',
    academyId: 'acad-1',
    academyName: '대치 엠스쿨 수학학원',
    type: 'check_in',
    title: '등원 완료 알림',
    message: '민준이가 [대치 엠스쿨 수학학원] 지오펜스(반경 80m)에 16:48 정상 진입하여 등원 처리되었습니다.',
    timestamp: '어제 16:48',
    isRead: false,
  },
  {
    id: 'notif-2',
    childId: 'child-1',
    childName: '이민준',
    academyId: 'acad-1',
    academyName: '대치 엠스쿨 수학학원',
    type: 'check_out',
    title: '하원 완료 알림',
    message: '민준이가 수업 종료 후 학원 반경을 벗어나 안전하게 귀가 중입니다 (19:04 출발).',
    timestamp: '어제 19:04',
    isRead: true,
  },
  {
    id: 'notif-3',
    childId: 'child-1',
    childName: '이민준',
    academyId: 'acad-1',
    academyName: '대치 엠스쿨 수학학원',
    type: 'warning_late',
    title: '지각 위험 경고',
    message: '수업 시작 10분 전이나 아직 학원 지오펜스 외부(거리 340m)에 있습니다. 확인이 필요합니다.',
    timestamp: '3일 전 16:50',
    isRead: true,
  },
  {
    id: 'notif-4',
    childId: 'child-1',
    childName: '이민준',
    academyId: 'acad-1',
    academyName: '대치 엠스쿨 수학학원',
    type: 'shuttle',
    title: '셔틀버스 탑승 10분 전 안내',
    message: '노란 1호차가 은마아파트 3동 정문으로 16:30 도착 예정입니다. 탑승을 준비해 주세요.',
    timestamp: '어제 16:20',
    isRead: true,
  },
];

export const MOCK_SCHOOL_TIMETABLE: SchoolClassPeriod[] = [
  { period: 1, subject: '국어', teacher: '김진희 T', room: '2-3 교실' },
  { period: 2, subject: '영어', teacher: '이수민 T', room: '어학실 2' },
  { period: 3, subject: '수학', teacher: '정호석 T', room: '2-3 교실' },
  { period: 4, subject: '과학 (물리)', teacher: '최동욱 T', room: '과학관 1실' },
  { period: 5, subject: '체육', teacher: '한기준 T', room: '체육관' },
  { period: 6, subject: '역사', teacher: '윤서아 T', room: '2-3 교실' },
];

export const MOCK_SCHOOL_MEAL: SchoolMealItem = {
  date: '2026-09-17',
  mealType: '중식',
  menu: [
    '찰흑미밥',
    '소고기미역국 (국내산 한우)',
    '돈육간장불고기 (국내산 돼지고기)',
    '상추쌈 / 수제쌈장',
    '배추김치',
    '친환경 샤인머스캣',
  ],
  calories: '685.4 Kcal',
  originInfo: '쌀(국내산), 쇠고기(국내산한우), 돼지고기(국내산), 김치(국내산)',
  allergies: ['대두', '밀', '돼지고기', '쇠고기', '아황산류'],
};

export const INITIAL_HOMEWORKS: HomeworkItem[] = [
  {
    id: 'hw-1',
    childId: 'child-1',
    academyId: 'acad-1',
    academyName: '대치 엠스쿨 수학학원',
    title: '수학 심화 쎈 35p ~ 42p 오답노트 작성',
    dueDate: '2026-09-18',
    isCompleted: false,
    priority: 'high',
  },
  {
    id: 'hw-2',
    childId: 'child-1',
    academyId: 'acad-2',
    academyName: '청담 에이프릴 어학원',
    title: 'Word Master Ch.14 80단어 암기 및 테스트 준비',
    dueDate: '2026-09-19',
    isCompleted: true,
    priority: 'medium',
  },
  {
    id: 'hw-3',
    childId: 'child-1',
    academyId: 'acad-3',
    academyName: '미래탐구 과학실험관',
    title: '산화환원 실험 보고서 사전 가설 작성',
    dueDate: '2026-09-20',
    isCompleted: false,
    priority: 'low',
  },
];

export const INITIAL_FAMILY_MEMBERS: import('./types').FamilyMember[] = [
  {
    id: 'mem-mom',
    name: '엄마 (이지혜)',
    role: 'parent',
    relation: '엄마',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    color: '#EC4899', // Pink
  },
  {
    id: 'mem-dad',
    name: '아빠 (이진호)',
    role: 'parent',
    relation: '아빠',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    color: '#3B82F6', // Blue
  },
  {
    id: 'child-1',
    name: '이민준',
    role: 'child',
    relation: '첫째 (중2)',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    color: '#6366F1', // Indigo
  },
  {
    id: 'child-2',
    name: '이서연',
    role: 'child',
    relation: '둘째 (초5)',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    color: '#10B981', // Emerald
  },
];

export const INITIAL_CALENDAR_EVENTS: import('./types').CalendarEvent[] = [
  {
    id: 'ev-1',
    title: '민준 수학 중간 모의평가',
    category: 'academy',
    date: '2026-09-18',
    startTime: '17:00',
    endTime: '19:00',
    memberIds: ['child-1', 'mem-mom'],
    location: '대치 엠스쿨 수학학원 본관 302호',
    description: '이차방정식 심화 및 도형 단원 실전 모의고사 (지오펜스 자동 체크인)',
    color: '#3B82F6',
    isSyncedFromAcademy: true,
    academyId: 'acad-1',
  },
  {
    id: 'ev-2',
    title: '서연 소아치과 정기 검진',
    category: 'medical',
    date: '2026-09-19',
    startTime: '11:00',
    endTime: '12:00',
    memberIds: ['child-2', 'mem-mom'],
    location: '강남 연세주니어치과 (한티역 3번 출구)',
    description: '교정 정기 체크 및 불소 도포 예약',
    color: '#EF4444',
  },
  {
    id: 'ev-3',
    title: '가족 주말 한강 피크닉 & 라이딩',
    category: 'family',
    date: '2026-09-20',
    startTime: '14:00',
    endTime: '18:00',
    memberIds: ['mem-mom', 'mem-dad', 'child-1', 'child-2'],
    location: '반포한강공원 달빛광장',
    description: '가족 자전거 라이딩 및 돗자리 피크닉 도시락',
    color: '#F59E0B',
  },
  {
    id: 'ev-4',
    title: '대치중학교 2학기 학부모 진학설명회',
    category: 'school',
    date: '2026-09-21',
    startTime: '14:00',
    endTime: '16:00',
    memberIds: ['child-1', 'mem-mom', 'mem-dad'],
    location: '대치중학교 대강당',
    description: '고입 입시 로드맵 및 2학기 교과 과정 안내 (나이스 연동)',
    color: '#8B5CF6',
    isSyncedFromSchool: true,
  },
  {
    id: 'ev-5',
    title: '서연 에이프릴 스피킹 테스트',
    category: 'academy',
    date: '2026-09-22',
    startTime: '16:30',
    endTime: '18:30',
    memberIds: ['child-2'],
    location: '청담 에이프릴 어학원 5층 스마트랩',
    description: 'Junior TOEFL Speaking Level-up Test',
    color: '#8B5CF6',
    isSyncedFromAcademy: true,
    academyId: 'acad-2',
  },
  {
    id: 'ev-6',
    title: '가족 외식 (민준 수학 100점 축하)',
    category: 'family',
    date: '2026-09-25',
    startTime: '19:30',
    endTime: '21:00',
    memberIds: ['mem-mom', 'mem-dad', 'child-1', 'child-2'],
    location: '대치동 한우 명가',
    description: '온 가족 함께 저녁 식사 예약 완료',
    color: '#F59E0B',
  },
  {
    id: 'ev-7',
    title: '민준 미래탐구 과학캠프 발표',
    category: 'academy',
    date: '2026-09-26',
    startTime: '10:00',
    endTime: '13:00',
    memberIds: ['child-1', 'mem-dad'],
    location: '미래탐구 과학실험관 201호',
    description: '산화환원 탐구 프로젝트 가족 참관 발표',
    color: '#10B981',
    isSyncedFromAcademy: true,
    academyId: 'acad-3',
  },
];

export const INITIAL_CHAT_MESSAGES: import('./types').ChatMessage[] = [
  {
    id: 'msg-1',
    senderId: 'mem-mom',
    senderName: '엄마 (이지혜)',
    senderRelation: '엄마',
    senderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    senderRole: 'parent',
    text: '민준아 오늘 수학학원 셔틀 16:30 은마 3동 정문이야! 늦지 않게 준비해~',
    timestamp: '16:22',
    readCount: 3,
  },
  {
    id: 'msg-2',
    senderId: 'child-1',
    senderName: '이민준',
    senderRelation: '첫째',
    senderAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    senderRole: 'student',
    text: '네 엄마 지금 가방 챙겨서 정문 앞이에요! 노란 1호차 도착했습니다 🚌',
    timestamp: '16:26',
    readCount: 3,
  },
  {
    id: 'msg-3',
    senderId: 'mem-dad',
    senderName: '아빠 (이진호)',
    senderRelation: '아빠',
    senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    senderRole: 'parent',
    text: '민준이 학원 잘 도착했네 👍 서연이는 태권도 끝나고 아빠가 픽업갈게.',
    timestamp: '17:15',
    readCount: 3,
  },
  {
    id: 'msg-4',
    senderId: 'child-2',
    senderName: '이서연',
    senderRelation: '둘째',
    senderAvatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    senderRole: 'student',
    text: '아빠! 저 오늘 태권도 줄넘기 급수 심사 통과했어요! 상장 사진 보냅니다 🥋✨',
    timestamp: '17:20',
    attachment: {
      name: '태권도_급수승급_인증서.jpg',
      size: '2.4 MB',
      type: 'image',
      url: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?w=600&auto=format&fit=crop&q=80',
    },
    readCount: 3,
  },
  {
    id: 'msg-5',
    senderId: 'mem-mom',
    senderName: '엄마 (이지혜)',
    senderRelation: '엄마',
    senderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    senderRole: 'parent',
    text: '우리 서연이 정말 대견해라! 오늘 저녁에 맛있는 거 먹자 ❤️',
    timestamp: '17:22',
    readCount: 3,
  },
  {
    id: 'msg-6',
    senderId: 'child-1',
    senderName: '이민준',
    senderRelation: '첫째',
    senderAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    senderRole: 'student',
    text: '수업 끝나서 하원 지오펜스 통과했어요! 오늘 수학 오답노트 숙제 파일 미리 올려둡니다.',
    timestamp: '19:05',
    attachment: {
      name: '수학_심화_오답노트_1차.pdf',
      size: '1.2 MB',
      type: 'pdf',
      url: '#',
    },
    locationShare: {
      name: '대치 엠스쿨 수학학원 정문',
      lat: 37.4982,
      lng: 127.0598,
    },
    readCount: 2,
  },
];

